name:  FutballBola
version: '1.0-SNAPSHOT'
main: com.lubodi.futbollwachu.FutballBola
api-version: '1.20'
commands:
  arena:
    description: Comando principal
  futbol:
    description: Comando principal de fútbol
  adminArena:
    description: Only for OP's used to create a new arena