required-players: 1
countdown-seconds: 10
countdownGame-seconds: 60
countdownEnd-seconds: 10
max-portero: 2
lobby-spawn:
  world: 'world'
  x: -3
  y: 77
  z: -36
  yaw: -180
  pitch: 0
arenas:
  0:
    name: 'default'
    world: 'world'
    teams:
      RED:
        name: "Team1"
        color: "GREEN"
        zona:
          world: 'world'
          x: -87
          y: 41
          z: 855
          yaw: -180
          pitch: 0
          x2: -46
          y2: 51
          z2: 901
          yaw2: -180
          pitch2: 0
        portero:
          world: 'world'
          x: -76
          y: 45
          z: 887
          yaw: -180
          pitch: 0
          x2: -87
          y2: 41
          z2: 869
          yaw2: -180
          pitch2: 0
        cancha:
          world: 'world'
          x: -87
          y: 41
          z: 876
          yaw: -180
          pitch: 0
          x2: -89
          y2: 45
          z2: 881
          yaw2: -180
          pitch2: 0
      BLUE:
        name: "Team2"
        color: "AQUA"
        zona:
          world: 'world'
          x: -44
          y: 41
          z: 901
          yaw: -180
          pitch: 0
          x2: -3
          y2: 51
          z2: 855
          yaw2: -180
          pitch2: 0
        portero:
          world: 'world'
          x: -14
          y: 41
          z: 887
          yaw: -180
          pitch: 0
          x2: -4
          y2: 46
          z2: 869
          yaw2: -180
          pitch2: 0
        cancha:
          world: 'world'
          x: -4
          y: 41
          z: 876
          yaw: -180
          pitch: 0
          x2: -1
          y2: 45
          z2: 881
          yaw2: -180
          pitch2: 0
    ball-spawn:
      world: 'world'
      x: -45
      y: 44
      z: 878
      yaw: 0
      pitch: 0
    spawn:
      world: 'world'
      x: -45
      y: 41
      z: 878
      yaw: 0
      pitch: 0
